### ISSUE TITLE
Metadata - Consider not using product-specific categories

### ISSUE THREAD

**Issue by macandcheese** [Esri/calcite-ui-icons#304]
Over the last few releases, there have been many icons added under product-specific categories. 

This leads to some icons that have related concepts in other categories not being grouped together:

<img width="1027" alt="Screenshot 2023-09-22 at 12 28 40 PM" src="https://github.com/Esri/calcite-ui-icons/assets/4733155/7a8ba596-8d7a-4069-a4ae-30d4309d0762">
<img width="258" alt="Screenshot 2023-09-22 at 12 35 47 PM" src="https://github.com/Esri/calcite-ui-icons/assets/4733155/00d6b755-5da8-459f-8c4d-29360e060ad5">
<img width="1011" alt="Screenshot 2023-09-26 at 9 43 53 AM" src="https://github.com/Esri/calcite-ui-icons/assets/4733155/039354ce-097e-41ff-9b09-197adb4d8946">

Because these are also used by our design system consumers - this is kind of a confusing change in the presentation of some of the icons. The icon search experience is driven by these category chips, and is a frequent workflow for our internal and external users to find appropriate icons.

Would it be possible to re-classify all of these recently added icons into the prior set of categories? Many have keywords, related concepts, or similar icons in existing categories. I understand the desire to tag these by team for team tracking purposes, but could these maybe be keywords instead of categories?

**Comment by allieorth** [comment]
Hey Adam — this has been coming up recently, and there are a couple other considerations on our team's end.

Firstly some background on the _categories_: 
Categories were included in our icon tags for the[ reference page we manage](https://esri.github.io/calcite-ui-icons/), it isn’t a searchable/clickable item, it's there to inform what source file the artwork lives in. The categories were only intended to be viewable for the benefit of the icon design team to easily find source artwork, and for that reason we need them to be fairly casual and able to grow with the library. Categories were never intended to be a concise clean reference for users.

Since the categories are intended to help us organize artwork, it's important to keep a file like Knowledge Graph containing all the node based icons for consistency. If we sort these out to, say, GIS concepts they get distilled into 6+ individual files making it a less usable resource for our team.
If we would have known that these categories would be user facing we may have made some different organizational decisions at the beginning to prioritize cleaner and more accurate categorization. 

Is there a chance that some of the organizational change you're looking for could be achieved by eliminating the category chips all together and encouraging use of the more robust, specific and accurate tags applied to each icon?
Or if you like the category tags, but don’t like how the icon team tags them could ya’ll redo the tags in a way thats cleaner and more usable on your site? 

**Can we just inventory and re-classify all the icons?**
Before we go to the work to retag and reorganize, it would he helpful to get some more concrete data on the usefulness of these category chips. Then we would be empowered to make a decision if its worth the work to redo category tagging, rethink file organization, move source artwork, and rethink our team’s keyword tagging workflows.

Lets figure out if this is useful to the user:

1. Is there some background on the importance of filtering by categories and why its necessary in conjunction with searchable tags? 
2. Do we have feedback that users find it useful?
3. How many people are actually visiting and using this reference page? 
4. How many people are clicking on the categories filters?

Once we get some answers to these we can decide how to proceed and on what timeline. As an added note, our team is looking to hire an asset management specialist (actively recruiting) and this would be a great project for them once hired if the timeline allows. 

Thanks Adam, appreciate your thoughts as we continue to figure this out!

**Comment by macandcheese** [comment]
Thanks for the thoughts! 

From the "I'm a user looking for icons" - yes, we can see through metrics that the majority of users have at least one category active when browsing (via url query parameter). This experience is reasonably common, you can see similar browsing experience from [Google Symbols](https://fonts.google.com/icons), [Carbon](https://carbondesignsystem.com/guidelines/icons/library/), and many other design systems have the option to filter by one or more category. Font Awesome, etc., are predicated upon this interaction. 

Calcite doesn't want to manage the tags on behalf of the icon team, as I mentioned I understand the need to maintain associative metadata for requesting team. But Calcite's users (and by extension, Esri's developer community), expect icons to be grouped by concept, and existing category.

This seems to have been a recent change, over the last couple of releases, which is why I brought it up at this point. I'm not suggesting a re-categorization of the entire set, just the couple dozen that have been recently added with these new "product" types of keywords.

**Comment by allieorth** [comment]
Thanks for this! Some of the clarification and numbers were super helpful.
We recognize that the categories aren’t perfect and think some work can go into consolidating and cleaning up the category tags.

I can see the duplicate "Knowledge Graphics" category going away - being merged with "Knowledge Graph". I do think we need to keep Knowledge Graph as a category, and even though that category looks product specific, it isn't. (I don’t think ArcGIS Knowledge even uses calcite UI icons…?)
Multiple teams use knowledge graph icons and since there are so many of them its helpful to categorize them together.

Perhaps "Web Editor" could just be "Editing". Editing would be a good category for many concepts.

"Raster Function Template" could be spread between other existing categories. As can the newly created Indoors category.

I will also have our team be more mindful when creating new categories, and ensure they are actual categories and not just products. 

I am also wondering if you think it would be disruptive to anything if we added a tag what was just letters and numbers to help with our file orginization? eg `04f`? That way we could focus on keeping the categories clean while still having an accurate file location record. 

I can get started making those changes if you think that sounds good on your end!

---

One additional question I have is how are you powering this ArcGIS developers webpage? Is this powered by the files on the github repo?
If so, I’m concerned with the longevity of this work flow. Those files are created using custom code and macros created by folks who no longer work at Esri and those are slowly beginning to fail us. As of right now only 2/7 people on our team can exicute the macros to launch the refrence page and generate the sprites and files needed to power it.

If ya’ll are relying on those files as well thats an even larger reason we need to get some help trouble shooting. LMK if you have any insight there 

Thanks again!

**Comment by macandcheese** [comment]
I do tend to think "Editing" is a little generic - it would still seem to separate related concepts like in the above screenshots (separating the cursor from all other cursors, or the layer from all other layers). 

But, ultimately that is up to your team how they are tagged. It was just a much cleaner story for our external users until a month or two ago.

It might be worth exploring adding a section for "internal tags" that we can decide not to display to our external developer customers, since to an external user  (or even internal designers on product teams)`04f` isn't valuable, but I understand it is to the icon team. That said, if its just a tag, not a category, it will only be seen when a user clicks to the detail view of an icon.


The developer site uses the same source as the reference page - just the raw image paths and the keywords file, so it's all automated. cc @SkyeSeitz for discussion regarding the issues with deployment - it's not related to the developer site but sounds like we need to get something fixed there.

**Comment by allieorth** [comment]
Great, sounds good. I'll work with my team on getting those categories cleaned up and check in with you if we run into questions/considerations that would be helpful for you to weigh in on. 

If you're not worried about adding that "source file code" tag i think that would help us out. We could discuss making it an "internal tag" but that would disrupt the code builder we have in place and would be more work...

Thanks for tagging @SkyeSeitz — they are semi familiar with some of the problems we've been encountering but I was't super sure if it was in your wheelhouse, Skye, to help there. If you've got the time we can chat more about it on teams or you can help redirect me to someone else if that's what needs to happen. Thanks!!

**Comment by SkyeSeitz** [comment]
Thanks, y'all. Yes, happy to chat anytime, Allie. Might be worth it for the Icon Team to pursue acquiring an official dev support contact/position. Not sure from which team it would come and I can't personally volunteer someone 😂, but maybe Steve can chat with the powers that be to see what is possible.
