### ISSUE TITLE
Icon Requests: Projects and Plans

### ISSUE THREAD

**Issue by nata9923** [Esri/calcite-ui-icons#38]
Hey Icon guys,

We’re building ArcGIS Urban and have two icon requests:
1. A bulldozer - to represent urban planning projects
2. A zoning/parcel icon - to represents plans 

Currently we are using:
<img width="434" alt="screenshot 2019-01-23 at 10 49 00" src="https://user-images.githubusercontent.com/44285703/51597882-9c09f180-1efc-11e9-9cd7-b87ad6e72cb7.png">

How do we go about getting something like these made available in the Calcite UI icon set? 
Thanks

**Comment by nata9923** [comment]
@paulcpederson @KatelynSeitz

**Comment by paulcpederson** [comment]
@nata9923 your parcels icon looks pretty similar to the "selection" icon. It's tagged as `generic` `map` `GIS` `area`, so seems like using it to indicate parcel areas wouldn't be too much of a stretch. @KatelynSeitz or @johnmgriffith would be the real experts, though

**Comment by nata9923** [comment]
@johnmgriffith @paulcpederson @KatelynSeitz 

In Urban, there is a public facing "overview" of your city. When arriving at the App the user will see their city, plus a floating panel on the left with a search input field and the above icons:
<img width="1301" alt="screenshot 2019-01-25 at 08 56 43" src="https://user-images.githubusercontent.com/44285703/51732823-c59f5600-207f-11e9-8dd9-be56d8265303.png">

When user clicks one of the icons, a list of the current plans/projects within your city will expand: 
<img width="405" alt="screenshot 2019-01-25 at 08 59 22" src="https://user-images.githubusercontent.com/44285703/51732850-df409d80-207f-11e9-898e-d85ed6e95d23.png">

The icon represents a concept rather than an action.

**Comment by nata9923** [comment]
Hey @johnmgriffith  @paulcpederson  @KatelynSeitz 

Any news?

**Comment by johnmgriffith** [comment]
Hi @nata9923,

Yes, Katelyn and I have been discussing this. We think that this would work best as Calcite UI icons, but we recommend that you use the outlined style, since that's our default primary style. 

We don't field requests through GitHub, so please submit a Workfront request for these 4 icons so that we can get them in our queue. Once the icon request is approved, we'll set up a meeting with you to talk about the concepts in better detail.

You can submit a new request by clicking "New Request" here, choosing "Icon", and filling out the form fields: https://esri.my.workfront.com/requests

**Comment by johnmgriffith** [comment]
@nata9923, did you ever submit a request for these two icons? Or can we close out this issue?

**Comment by nata9923** [comment]
@johnmgriffith, I submitted a request. You can close this.
