### ISSUE TITLE
"mixed state" Eye

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-ui-icons#46]
We previously had three states for the icon:
"visible" | "mixed" | "hidden"

something like this.

![image](https://user-images.githubusercontent.com/12503298/54240598-c2e7ab80-44db-11e9-9f36-5bc435e07ad7.png)

Can we bring back the mixed state?
One use case for this is this:
> Layer is set to visible but because of the current scale of the map, its symbols are hidden.

A layer may be configured to only show at specific map scales because its symbology only works correctly at those scales.

@KatelynSeitz @johnmgriffith @sfrizzell @driskull

**Comment by johnmgriffith** [comment]
I see. Looking at the reference page, swapping between outlined and filled doesn't really work either because the line weights are different. Since there isn't currently a "visible" version of the eye in the outlined set, then we'd need to make some adjustments to the names to accommodate the two states.

My vote is that we should turn this into an official request.

**Comment by asangma** [comment]
Sounds good.

**Comment by asangma** [comment]
Request submitted.

**Comment by KatelynSeitz** [comment]
issue resolved in [1.6.5](https://github.com/Esri/calcite-ui-icons/releases/tag/v1.6.5) release.
