### ISSUE TITLE
Average symbol

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-ui-icons#48]
Do you already have an SVG for this concept:
![xAvg](https://user-images.githubusercontent.com/12503298/54396566-b3e63200-4670-11e9-84f4-dde2da3e8884.png)

It is currently used to indicate the average in a histogram. In this case 👇 , we are looking at it in the vertical smart mapping histogram slider, but it may also show up in a horizontal histogram...dunno if that matters.
![Screen Shot 2019-03-14 at 3 49 33 PM](https://user-images.githubusercontent.com/12503298/54396635-e7c15780-4670-11e9-956e-51a688af4c80.png)

@johnmgriffith @KatelynSeitz @mitc7862

**Comment by asangma** [comment]
Also, the PNG on ArcGIS Online is called `xAvg.png`.

**Comment by asangma** [comment]
<img width="201" alt="slider-with-xavg" src="https://user-images.githubusercontent.com/12503298/54396815-8c439980-4671-11e9-8b67-fd367660ad48.png">

**Comment by paulcpederson** [comment]
An icon would be nice, but you could theoretically get away with rendering the "x-bar" character in plain text with an italic serif like this: https://codepen.io/paulcp/pen/GeQaao

**Comment by KatelynSeitz** [comment]
I don't believe we have an icon for this right now, but we can add it to the Calcite-UI set if it would be helpful. Outside of being an indicator, does this concept represent any other functions?

**Comment by asangma** [comment]
I imagine it could be used for something like "show the average". @mitc7862 What do you think?

@paulcpederson 
>  you could theoretically get away with rendering the "x-bar" character in plain text

I can see that. I think it'd also be nice to have nicely rendered versions of the symbol at the different sizes that would match with the other Calcite-UI icons without needing to add font-size, line-height, etc.

**Comment by mitc7862** [comment]
I don't know of an existing use-case for a "show average" feature that exists apart from other statistics, And using "_x̄_ " as the main Icon for a general statistics feature wouldn't make much sense (IMO). Having a **set of common statistical symbols** would be nice _potentially_, but like I said, I'm not sure when/where they'd be used. 

I'm inclined toward using unicode symbols for these since they are generally used as labels and should probably respond to the font size being set for labels. (Using a 16px icon in this context will seem too large). I've also been reprimanded once by an epidemiologist that the "_x̄_" _has_ to be set in _Times New Roman_. I haven't been able verify if this is true outside of academia though.

**Comment by asangma** [comment]
@mitc7862 You're either required in or banned from these discussions from here on out.

**Comment by asangma** [comment]
But seriously, solid stuff Mitch.

There might be some implementation requirements. Stand by.

**Comment by asangma** [comment]
Aight...checked in with the man @jonuihlein, and we are good to use the HTML entity as you suggested @paulcpederson.

Closing.
