### ISSUE TITLE
General: Sizing alignment with rectangular icons.

### ISSUE THREAD

**Issue by asangma** [Esri/calcite-ui-icons#51]
Hai.

So, sometimes icons that are generally rectangular are the full width or height of their containers and sometimes they've got some padding. While I understand how this can result from the requirements of some of the shapes, it can sometimes look weird in interfaces.

![image](https://user-images.githubusercontent.com/12503298/55660930-aa5a7080-57bd-11e9-9501-a6268efd86b9.png)
Showing a few 24 icons.

Any thoughts?

**Comment by asangma** [comment]
@KatelynSeitz @johnmgriffith

**Comment by asangma** [comment]
Feel free to tell me to
![doge with it](http://66.media.tumblr.com/b677b6b70be6235fbfe8797d6ce59734/tumblr_n6euc1ZIIw1txy0q2o1_400.gif)

**Comment by johnmgriffith** [comment]
Looking at this again, yeah the table and the image have a huge discrepancy in size. I think that's something that we could work on.

**Comment by sfrizzell** [comment]
![image](https://user-images.githubusercontent.com/13968230/59290725-175f0c00-8c2e-11e9-95ea-cac6edd24361.png)

This is likely caused by a desire to make image and image-mensuration use the same size base element. Consistent visual weight (as much as possible) would hep to reduce the scale issue when icons are remixed in different combinations. I think the Images icon is a little small too. @johnmgriffith @KatelynSeitz we may need to do a visual weight review of the library to see what assets are out of scale.

![images](https://user-images.githubusercontent.com/13968230/59290905-876d9200-8c2e-11e9-80a6-df8209cf42f9.png)

**Comment by julio8a** [comment]
Checking in on this, will updates for these icons be in the big update release coming up?

**Comment by KatelynSeitz** [comment]
resolved in Calcite 3.0.0 Beta
