### ISSUE TITLE
Some icons are not centered in the viewbox

### ISSUE THREAD

**Issue by spatialdude** [Esri/calcite-ui-icons#60]
Hi

I'm finding that some icons are not properly centred in their viewbox. As we use the icons directly in our apps (e.g. Survey123) this causes a problem that the icon then isn't centred correctly when draw.

e.g. 
https://github.com/Esri/calcite-ui-icons/blob/master/icons/gps-on-24.svg

The offset can also be seen when opening the SVGs in Illustrator. e.g. 

![image](https://user-images.githubusercontent.com/7235583/58939967-acd84700-87bb-11e9-8365-3e8905e8da6c.png)

**Comment by johnmgriffith** [comment]
Due to the nature of icon design, and designing in a grid with an 8-bit system (16, 24, 32) the viewbox has to be an even number. So for our outlined icon library… our circles, squares, and all other sorts of shapes that have an element in the center (such as an exclamation mark, plus, minus, etc.), we are required to move the icon slightly from the center of the viewbox, otherwise the icon would split pixels and appear blurry.

The alternative is an icon that has a thicker, even-number line weight, which is what the filled set is supposed to accomplish:

gps-on-24-f.svg
![image](https://user-images.githubusercontent.com/30184050/58986082-830a2a80-8791-11e9-8916-d8e4ca206e4c.png)


If the icon needs to be centered exactly in the center of the viewbox, then you'll need to use the filled icon. Please contact me if you still have any questions.

**Comment by spatialdude** [comment]
Thanks for the explanation @johnmgriffith . In this case the filled icons looked a bit too heavy for where it was being used.

What might fix it in our case if the view box was tight to the icon in the horizontal axis. I'm trying to figure out a way to use the icons that look best in a given use case without having to modify or convert them in any way. Unfortunately there is no hint that I can think of that would allow an auto calculated adjustment to the centring to be made without figuring it out on a case by case basis.

**Comment by TheBlueDog** [comment]
We've wanted to use the filled icon as a hover/selected stated in some cases and were not able to do that because the two versions don't overlay each other nicely.

**Comment by johnmgriffith** [comment]
In general, when it is impossible to have an exact center point for an icon due to the even pixel problem, our unwritten rule has been to gravitate the icon to the top-left corner. This GPS icon is an exception to that rule for some reason, and in my searching I've found a lot of other exceptions to that rule.

Would you say that it's worthwhile to make that reasoning consistent? That way our icons like `move`, `plus`, `x`, `gps`, `pan` and `pan-drag` are all shifted so the icon's visual center point is towards the top left corner of the viewbox?

**Comment by johnmgriffith** [comment]
Not all the icons are the same size, so I think there'd still be a need for some slight adjustments on a case by case basis, but it should generally take care of most situations.

**Comment by TheBlueDog** [comment]
Consideration needs to be made when the icons are put inside a border, like a button, where its the only object in it. In the UI we want the icon to be centered within its container. In other cases, icons will be placed next to each other in a row which could be horizontal or vertical, and they need to align with each other.

**Comment by spatialdude** [comment]
@TheBlueDog Yes I had the same problem. It would be ideal if an icons of the same base name +  filled/unfilled - have the same symmetry and line up over each other so that can be alternated dynamically in the app.

To some extent to that the left/right up/down icons also are symmetrical on their main visual axis that that when they are flipped horizontally/vertically they do not appear to shift. 

This also helps ensure cases where they are rotated. e.g a down care rotating 90 degrees when indicating something that is open/closed. In Survey123 the rotation is animated. So far I've found it ok.

![image](https://user-images.githubusercontent.com/7235583/58995213-9e7b4100-8836-11e9-8add-50e47ff49949.png)

![image](https://user-images.githubusercontent.com/7235583/58995236-ae932080-8836-11e9-8dc8-c79f50792531.png)

**Comment by johnmgriffith** [comment]
We have limitations on how much the filled/unfilled versions can match each other since the line weights are different. That's the nature of having a set with two styles that are set at 1px for the light set, and 2px for the heavy set. In fact, I think "light" and "heavy" is a better way to describe our styles than "unfilled" and "filled".

Note that for the left/right/up/down icons, we created individual assets for each of those because if we just provided a "caret" icon by itself, then it would have to sacrifice blurriness for being on pixel and having the ability to rotate. In that case, designing unique assets for each of them allowed us the best of both worlds. But these were a limited set of directional icons, and we don't have the luxury of doing that for every icon.

As stated before, because of the even pixel problem, our "light" icons will sometimes never be able to perfectly center in the middle of the viewbox because they are designed at 1px in an 8-bit grid. In the cases where that's a problem, it's up to the designer to find a UI solution that makes the icon look as good as possible in its individual context.

**Comment by johnmgriffith** [comment]
**Summarized:**

Light icons can't always match the heavy/filled icons due to line weight differences.

If light icons have an object that needs to be positioned in the exact middle vertical or horizontal of the icon (like a plus or a target) it has to be shifted by one pixel otherwise it'll be blurry.

**Comment by TheBlueDog** [comment]
I think that some sacrifice in the blurriness is acceptable in exchange for the usability.

**Comment by TheBlueDog** [comment]
For the caret example (and chevrons), its better to rotate them through css. That way we get the benefit of the animation. In which case, having it centered within the viewbox is ideal so the animation is smooth.

**Comment by sfrizzell** [comment]
@spatialdude @TheBlueDog Can you provide screen captures of the situations you are facing where icon alignment in a button or in a horizontal or vertical row of icons is presenting an alignment issue?

**Comment by spatialdude** [comment]
Here is an example 

<img width="250" alt="image" src="https://user-images.githubusercontent.com/7235583/59316213-a63c5900-8d00-11e9-9582-340b8d2cc164.png">

The solution I'm thinking is to calculate the pixel offset and adding it to both axis accordingly.
 eg.  x + 23/24 * scaledPixelSize

**Comment by sfrizzell** [comment]
Thanks for the example Elvin. We will need to consider our options further. Nudging an icon over half a pixel makes details blurry. Blurry is more of an issue on small icons as found in Calcite UI. Here is a before/after example of two 16px icons nudged over half a pixel...
![pixel_alignment](https://user-images.githubusercontent.com/13968230/59316538-e73a5c00-8c73-11e9-97a6-15a792a5bf0f.png)

**Comment by spatialdude** [comment]
@sfrizzell A thoughts from an app's perspective -

- Compensating for the offset isn't really a huge issue if it has to be done, it's more about how to determine which icons need an offset in each axis (and how many pixels respectively) without having to code especially for each.
- I was thinking of having some sort of exception table that lists icons by name and their respective x and y offsets so that when we use them, we can automatically calculate the offsets in one routine rather than case by case. If the exception table could be read (e.g. from a  JSON file in the repo) then that would be great as everyone could then use it Anything not in the exception table would be considered centred. (x/y offset is 0)
- In reality we don't draw the icons at the same pixels as defined by the view box. They almost always scaled as the pixel density of most systems these is quite high. So even the highest resolution icons (-32) still have to be scaled up as 32 physical pixels could be very small. As such a ½ logical pixel offset may still translate to an even physical pixel offset hence blurring should not occur or at least be very minimal.

**Comment by TheBlueDog** [comment]
A few off the top of my head...

The centerline and rotation need to be considered. For example, it may be common to rotate through an animation a direction icon.

In this case, one arrow would be used and then when the user does an action we transform it to point another direction. In the case of most of the arrows, chevrons, and carets, they won't rotate cleanly.

<img width="479" alt="Screen Shot 2019-06-12 at 9 06 35 AM" src="https://user-images.githubusercontent.com/5419306/59353750-ac770900-8cf1-11e9-8cb2-a2445a67ad6e.png">

The chevrons have to be adjusted through css to move them in line with text as the point is not centered.

<img width="262" alt="Screen Shot 2019-06-12 at 9 07 00 AM" src="https://user-images.githubusercontent.com/5419306/59353946-11326380-8cf2-11e9-8fa4-5c5515f91a6f.png">

The icon meant specifically to be a spinner can't be rotated as it will wobble.

![Screen Shot 2019-06-05 at 9 09 00 PM](https://user-images.githubusercontent.com/5419306/59353989-2e673200-8cf2-11e9-9947-d0b7e4631b3b.png)

**Comment by sfrizzell** [comment]
There seems to be 2 issues in play (scale and usage).

1. Calcite UI icons are designed to be pixel perfect when implemented at 100%. This is optimization for low resolution displays. Since they are SVG files, they can display as the same size but use more pixels to do it on high resolution desktop displays or mobile displays.

2. Animating Calcite UI icons, placing them in button containers, and swapping outline and filled Calcite UI icons to reflect on/off states were not design criteria when the library was created.

We want the icon library to be versatile and therefore widely adopted but it is clear that there are tradeoffs when making a library to serve a lowest common denominator.

An "easy" answer to the issues faced would be to:
- not put the icons in close proximity to other icons or UI components where odd/even pixel alignment issues become apparent
- not animate the icons (spinner!)
- not swap the outline and filled icons to reflect icon states
- expect some challenges when scaling the icons

Seeing implementation issues clarifies our future options. We might need to:
1. adjust Calcite UI to better accommodate animation, centering in buttons, toggle state alignment, etc. (sacrifice clarity on low resolution display use where the clarity is needed most)
2. rethink icon usage patterns so that issues are minimized (use color/value change or other means to signify on/off, etc.)
3. expand Calcite UI to contain additional assets beyond the current lowest common denominator to serve high resolution needs

@julio let's discuss these issues at our next meeting.

**Comment by paulcpederson** [comment]
Could also make the artboards an odd pixel number (17x17, 25x25, 33x33). This would be a breaking change but would allow you to vertical/horizontal center everything while still on even pixels, I believe

**Comment by sfrizzell** [comment]
That is a good approach for the outline assets based on their 1 pixel (odd) line weight but then the filled assets wouldn't always center since they have 2 pixel line weights in many cases.

**Comment by sfrizzell** [comment]
...definitely worth exploring the odd pixel artboard implications

**Comment by julio8a** [comment]
Yes, let's review in our next meeting.

**Comment by TheBlueDog** [comment]
We do use icons in close proximity to each other in Track Viewer. 
<img width="1040" alt="Screen Shot 2019-06-12 at 1 04 27 PM" src="https://user-images.githubusercontent.com/5419306/59371303-a6455480-8d12-11e9-9e9d-eaefc3e92ee4.png">

**Comment by TheBlueDog** [comment]
I'd suggest revisiting how the filled icons are designed. Maybe they are based much more on the outlines. We could used more than one color/shade of gray as well.

**Comment by julio** [comment]
> @julio let's discuss these issues at our next meeting.

Hi - I'm not the Julio you are looking for.

**Comment by spatialdude** [comment]
I fairly sure changing the view box sizes to be tight to the icons would fix it in our app cases.

**Comment by spatialdude** [comment]
@TheBlueDog I experimented and created a font version - https://github.com/Esri/calcite-ui-icons/issues/56#issuecomment-515443066 I think I can use this to overcome the problems described in this issue. Rendering the icons via fonts allows a lot of flexibility with scaling and positioning, taking advantage of the font rendering environment and performance. A bit more experimentation is needed to see if it all works out as expected, but so far the results look promising.

**Comment by paulcpederson** [comment]
@julio8a should we spin off some of this stuff from @TheBlueDog into separate issues?

1. Should bump up the right arrow 1px as it would still be aligned to the pixel grid in that position.
2. Alter the chevron glyphs so they are vertically centered. The top and bottom edge may need to be altered to align to the grid
3. Center the spinner inside its artboard.

**Comment by julio8a** [comment]
Yeah, will split into issues and submit a Workfront request. It's good to start with the most common use cases.

**Comment by julio8a** [comment]
Submitted a WorkFront and bundled it all into one. Will do the same for the issue (#67). Closing this one out.

**Comment by TheBlueDog** [comment]
@spatialdude  I would recommend not using icon fonts. There are accessibility issues and your sizing is subject to the rules of your typography.

**Comment by TheBlueDog** [comment]
@paulcpederson  `Center the spinner inside its artboard.` I believe when the issue was brought up to the icon team regarding this non-centered issue (at the time it was the compass icon) their solution was to create a duplicate that was "animation friendly". So there are icons that are nearly identical in the library.
