### ISSUE TITLE
Update alignment: centered

### ISSUE THREAD

**Issue by julio8a** [Esri/calcite-ui-icons#67]
In the discussions for centering vs. pixel perfect, the short term solutions will be to tackle the most used icons for now. arrow(s), chevron(s) & spinner. 

1. Should bump up the right arrow 1px as it would still be aligned to the pixel grid in that position. 
2. Alter the chevron glyphs so they are vertically centered. The top and bottom edge may need to be altered to align to the grid 
3. Center the spinner inside its artboard. 

More information and discussion on the repo issue: 
https://github.com/Esri/calcite-ui-icons/issues/60

**Comment by johnmgriffith** [comment]
Spinners look like they are already centered.

**Comment by johnmgriffith** [comment]
This issue is being addressed in the conversation for the "caret 16 too small" issue.

https://github.com/Esri/calcite-ui-icons/issues/68

• All of the multi-directional icons will be centered in their artboards (with the exception of the 1px arrows)
• Each multi-directional will have 4 different directions (up down left right)
• All those icons can be flipped or rotated without issue.

We'll be including these updates in our new large release @KatelynSeitz and I are preparing.

**Comment by julio8a** [comment]
Great, thanks!

**Comment by paulcpederson** [comment]
🌈 ✨
