### ISSUE TITLE
Tablet, Desktop, Rotate

### ISSUE THREAD

**Issue by jordanisip** [Esri/calcite-ui-icons#9]
To pair with the `mobile` icon, it would be great to additionally have:

- Tablet
- Desktop
- Rotate

Example from another icon set:

![screenshot 2018-08-24 18 25 43](https://user-images.githubusercontent.com/5899/44610661-2540bf00-a7cb-11e8-8891-a814d79c6364.png)

Thanks!

**Comment by johnmgriffith** [comment]
@jordanisip thanks for your recommendation! Since these are brand new concepts that don't currently exist in our set, our policy is to use Workfront when requesting new icons. Our main pre-requisite is that there should be a current specific need that demands a new icon. If your app UI needs these concepts, we'd be happy to create them for you. 

You can make a new request for these through this site. The form should make the process pretty harmless:
https://esri.my.workfront.com/requests

**Comment by julio8a** [comment]
What's the status of this issue?

**Comment by jordanisip** [comment]
Finally got around to creating a Workfront request. Request ID: 305606. Let me know if there is anything else needed.

**Comment by johnmgriffith** [comment]
This issue was resolved in 1.6.1. Closing now.
